name: OhNoRadioShow
favicon: null
layout_spectrum: 0.90932
typography_spectrum: 0.6777
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2d2d2d'
    - '#d10101'
    - '#fe555b'
    - '#8532fe'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
