name: OhNoRadioShow
favicon: null
layout_spectrum: 0.3134983715135604
typography_spectrum: 0.36351379193365574
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.17393384268507361
  lightness: 0.8718106581363827
  saturation: 0.5234959681984037
  rhythmicContrast: 0.643315555062145
purpose: []
